language: julia
os: linux

julia:
        - 0.4
notifications:
        email: false

install:
        - julia -e 'Pkg.add("HDF5"); Pkg.add("FileIO")'
        
script:
        - julia -e 'Pkg.clone(pwd()); Pkg.test("EMIRT")'
