language: julia
os: linux

julia:
    - 0.7
    - 1.0
    - nightly

notifications:
        email: false
git:
    depth: 999999

install:
    - sudo apt-get install -y -qq hdf5-tools
script:
    - julia -e 'import Pkg; Pkg.develop(pwd()); Pkg.test("EMIRT")'
